name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 0.1.5
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  html: ^0.15.0
  quill_delta:
    git:
      url: https://github.com/lucygeneric/quill-delta-dart/
  quiver_hashcode:
    git:
      url: https://github.com/lucygeneric/quiver_hashcode.git

dev_dependencies:


